[meta]
name = "PBistory"
author = "Josephine"
category = "Race"
version = "0.0.1"
siteid = 532452342

[script]
dependencies = [ "GrindingStats", "mapinfo" ]
optional_dependencies = [ "NadeoServices" ]
timeout = 5000